# Generated by Django 4.2.7 on 2024-04-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_author_instructor_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='isbn',
        ),
        migrations.AlterField(
            model_name='course',
            name='genre',
            field=models.ManyToManyField(help_text='Select a genre for this course', to='catalog.genre'),
        ),
        migrations.AlterField(
            model_name='course',
            name='summary',
            field=models.TextField(help_text='Enter a brief description of this course', max_length=1000),
        ),
        migrations.DeleteModel(
            name='BookInstance',
        ),
    ]
