# Generated by Django 4.2.7 on 2024-04-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_course_isbn_alter_course_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the price of this course', max_digits=10, null=True),
        ),
    ]
